import GlobalState from "@/context";
import "./globals.css";
// import Head from "next/head";
import { Inter } from "next/font/google";
// import logo from "../../public/static/logo.png";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "UrbanMarket",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href={metadata.icon} />
      </Head> */}
      <body className={inter.className}>
        <GlobalState>
          <Navbar />
          <main className="flex min-h-screen flex-col mt-[65px]">
            {children}
          </main>
          <Footer />
        </GlobalState>
      </body>
    </html>
  );
}
